---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.10.24
  environments_path: ./test/environments
  data_bags_path: ./test/data_bags
  client_rb:
    environment: kitchen

platforms:
  - name: centos67
    driver_config:
      box: boxcutter/centos67
    attributes:
      system:
        primary_interface: eth1
      masala_haproxy:
        keepalive_vi_1:
          interface: eth1
        keepalive_vi_2:
          interface: eth2
        keepalive_vi_3:
          interface: eth3
  - name: centos71
    driver_config:
      box: boxcutter/centos71
    attributes:
      system:
        primary_interface: eth1
      masala_haproxy:
        keepalive_vi_1:
          interface: eth1
        keepalive_vi_2:
          interface: eth2
        keepalive_vi_3:
          interface: eth3
  - name: centos72
    driver_config:
      box: boxcutter/centos72
    attributes:
      system:
        primary_interface: eth1
      masala_haproxy:
        keepalive_vi_1:
          interface: eth1
        keepalive_vi_2:
          interface: eth2
        keepalive_vi_3:
          interface: eth3
  - name: ubuntu1404
    driver_config:
      box: boxcutter/ubuntu1404
    attributes:
      system:
        primary_interface: eth1
      masala_haproxy:
        keepalive_vi_1:
          interface: eth1
        keepalive_vi_2:
          interface: eth2
        keepalive_vi_3:
          interface: eth3
  - name: ubuntu1504
    driver_config:
      box: boxcutter/ubuntu1504
    attributes:
      system:
        primary_interface: eth1
      masala_haproxy:
        keepalive_vi_1:
          interface: eth1
        keepalive_vi_2:
          interface: eth2
        keepalive_vi_3:
          interface: eth3
  - name: debian82
    driver_config:
      box: boxcutter/debian82
    attributes:
      system:
        primary_interface: eth1
      masala_haproxy:
        keepalive_vi_1:
          interface: eth1
        keepalive_vi_2:
          interface: eth2
        keepalive_vi_3:
          interface: eth3

suites:
  - name: primary
    run_list: ["recipe[masala_haproxy::master]", "recipe[masala_ldap::master]"]
    driver:
      #vm_hostname: false
      network:
      - ["private_network", {ip: "10.10.10.11"}]
      - ["private_network", {ip: "10.10.20.11"}]
      - ["private_network", {ip: "10.10.30.11"}]
      customize:
        memory: 512
        cpus: 1
    attributes:
      system:
        short_hostname: 'lb-primary'
      openldap:
        slapd_master: 10.10.10.11
      haproxy:
        listeners:
          listen:
            lb_test:
              - balance roundrobin
              - bind 0.0.0.0:3389
              - maxconn 10
              - mode tcp
              - server app1 10.10.10.13:389
              - server app2 10.10.10.14:389
      masala_haproxy:
        keepalive_password: abcdefghij
        keepalive_vi_1:
          virtual_router_id: 30
          vip: '10.10.10.20'
          peer: '10.10.10.12'
        keepalive_vi_2:
          virtual_router_id: 31
          vip: '10.10.20.20'
          peer: '10.10.20.12'
        keepalive_vi_3:
          virtual_router_id: 32
          vip: '10.10.30.20'
          peer: '10.10.30.12'
  - name: backup
    run_list: ["recipe[masala_haproxy::backup]", "recipe[masala_ldap::slave]"]
    driver:
      #vm_hostname: false
      network:
      - ["private_network", {ip: "10.10.10.12"}]
      - ["private_network", {ip: "10.10.20.12"}]
      - ["private_network", {ip: "10.10.30.12"}]
      customize:
        memory: 512
        cpus: 1
    attributes:
      system:
        short_hostname: 'lb-backup'
      openldap:
        slapd_master: 10.10.10.11
        slapd_rid: 102
      haproxy:
        listeners:
          listen:
            lb_test:
              - balance roundrobin
              - bind 0.0.0.0:3389
              - maxconn 10
              - mode tcp
              - server app1 10.10.10.13:389
              - server app2 10.10.10.14:389
      masala_haproxy:
        keepalive_password: abcdefghij
        keepalive_vi_1:
          virtual_router_id: 30
          vip: '10.10.10.20'
          peer: '10.10.10.11'
        keepalive_vi_2:
          virtual_router_id: 31
          vip: '10.10.20.20'
          peer: '10.10.20.11'
        keepalive_vi_3:
          virtual_router_id: 32
          vip: '10.10.30.20'
          peer: '10.10.30.11'
  - name: app1
    run_list: ["recipe[masala_ldap::slave]"]
    driver:
      #vm_hostname: false
      network:
      - ["private_network", {ip: "10.10.10.13"}]
      customize:
        memory: 512
        cpus: 1
    attributes:
      system:
        short_hostname: 'app1'
      openldap:
        slapd_master: 10.10.10.11
        slapd_rid: 103
  - name: app2
    run_list: ["recipe[masala_ldap::slave]"]
    driver:
      #vm_hostname: false
      network:
      - ["private_network", {ip: "10.10.10.14"}]
      customize:
        memory: 512
        cpus: 1
    attributes:
      system:
        short_hostname: 'app2'
      openldap:
        slapd_master: 10.10.10.11
        slapd_rid: 104

